version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DefaultConnection=Host=dpg-d41p7v15pdvs73bdpg5g-a.oregon-postgres.render.com;Database=bdclientes_0bav;Username=admin;Password=UVw94ftbVgKc7yFm9yzOytQqOOJCmm23
